###
POST http://localhost:10000/api/alquileres HTTP/1.1
Content-Type: application/json

{
    "direccion": "Avenida Libertad #456",
    "fecha_entrega": "2024-04-15",
    "fecha_retorno": "2024-04-20",
    "estado": 2,
    "identificacion_cliente": 987654321,
    "nombreCompleto": "María García",
    "telefono": 5559876,
    "enseres": [
        {
            "cantidad": 8,
            "enser": "Mueble de TV"
        },
        {
            "cantidad": 12,
            "enser": "Mesa de centro"
        },
        {
            "cantidad": 5,
            "enser": "Sillas de plástico"
        }
    ]
}


###
GET http://localhost:10000/api/alquileres HTTP/1.1

###
GET http://localhost:10000/api/alquileres/ HTTP/1.1

###
DELETE http://localhost:10000/api/alquileres/ HTTP/1.1

### 
PUT http://localhost:10000/api/alquileres/ HTTP/1.1
Content-Type: application/json

{
    "direccion": "Avenida Libertad #456",
    "fecha_entrega": "2024-04-15",
    "fecha_retorno": "2024-04-20",
    "estado": 2,
    "identificacion_cliente": 987654321,
    "nombreCompleto": "Juan Sepulveda",
    "telefono": 5559876,
    "enseres": [
        {
            "cantidad": 8,
            "enser": "Mueble de TV"
        },
        {
            "cantidad": 12,
            "enser": "Mesa de centro"
        },
        {
            "cantidad": 5,
            "enser": "Sillas de plástico"
        }
    ]
}


