###
POST http://localhost:3000/api/alquileres HTTP/1.1
Content-Type: application/json

{
    "direccion": "Avenida Libertad #456",
    "fecha_entrega": "2024-04-15",
    "fecha_retorno": "2024-04-20",
    "estado": 2,
    "identificacion_cliente": 987654321,
    "nombreCompleto": "María García",
    "telefono": 5559876,
    "enseres": [
        {
            "cantidad": 8,
            "enser": "Mueble de TV"
        },
        {
            "cantidad": 12,
            "enser": "Mesa de centro"
        },
        {
            "cantidad": 5,
            "enser": "Sillas de plástico"
        }
    ]
}


###
GET http://localhost:3000/api/alquileres HTTP/1.1

###
GET http://localhost:3000/api/alquileres/6611b19d666653fbc52dccbe HTTP/1.1

###
DELETE http://localhost:3000/api/alquileres/6611af45643bf1177bfe69bd HTTP/1.1

### 
PUT http://localhost:3000/api/alquileres/6611b185666653fbc52dccb1 HTTP/1.1
Content-Type: application/json

{
  "nombre": "Nuevo Nombre",
  "apellido": "Nuevo Apellido",
  "telefono": "555-5678",
  "enseres": [
    {
      "_id": "6611b185666653fbc52dccb2",
      "cantidad": 20,
      "enser": "Sillas"
    },
    {
      "_id": "6611b185666653fbc52dccb3",
      "cantidad": 25,
      "enser": "Mesas"
    }
  ]
}

